### ISSUE TITLE
No data on Quicksight dashboard

### ISSUE THREAD

**Issue by aminembarki** [awslabs/discovering-hot-topics-using-machine-learning#15]
**Describe the bug**
No data on Quicksight dashboard
![image](https://user-images.githubusercontent.com/1456961/108366002-274b3380-71f8-11eb-9efe-b5be72350503.png)

- [ ] Version: **v1.1.0**
- [ ] Region: **[ us-east-1]**
- [ ] Was the solution modified from the version published on this repository? **No** 
- [x] Were there any errors in the CloudWatch Logs?
![image](https://user-images.githubusercontent.com/1456961/108365833-f408a480-71f7-11eb-8ea5-afdbe99a089a.png)

**Comment by knihit** [comment]
Hi aminembarki, sorry to hear that you are facing issues with the solution. If you can click on the 2nd tab on the dashboard (Text Analysis) and confirm that you are able to see the data.

For the first tab, the data is dependent on a job called topic modeling. This job is scheduled based on the cloudformation parameters specified at the time of deployment. If you deployed with default values, it is scheduled to run every midnight GMT:+00. Depending upon when you deployed the solution, you should be able to see the data in the first tab in the next 24 hours of your deployment. Please let me know if the issue is resolved and I will be happy to help you further in this regard.

Also if you have any other feedback based on your use case, please feel free to reach out. 

On a side note, in the documentation we did put out a note in this section: https://docs.aws.amazon.com/solutions/latest/discovering-hot-topics-using-machine-learning/step-2-configure-quicksight.html. But I do get the point that it is something that users will miss out. We will try and see if we can do a better job of making this more prominent/ visible.

**Comment by nihitkas** [comment]
Hi @aminembarki, please let us know if the above information helped to solve the problem. Are you are still facing the issue?

**Comment by aminembarki** [comment]
hi @knihit , @nihitkas 
thank you for  your help.  i deployed again today , i'm waiting  till  midnight GMT. to see if it works

**Comment by aminembarki** [comment]
Hello @knihit, 

No data, actually jobs  run at 00:00 UTC
![image](https://user-images.githubusercontent.com/1456961/108964217-7b806880-767b-11eb-874e-ecb85d31c210.png)

DynamoDB & S3 are empty .
![image](https://user-images.githubusercontent.com/1456961/108964404-b97d8c80-767b-11eb-845b-7a56b1a1d862.png)

Dashboard
![image](https://user-images.githubusercontent.com/1456961/108966214-31e54d00-767e-11eb-9161-4dbe221e2daf.png)

Athena All tables are empty .
![image](https://user-images.githubusercontent.com/1456961/108966425-707b0780-767e-11eb-89da-2827b42257d7.png)


Do i need to set twitter API  Keys somewhere ? 

thank you guys for  this awesome project.

**Comment by aminembarki** [comment]
Thank you  @knihit , @nihitkas . works for me

**Comment by knihit** [comment]
Hi @aminembarki , thank you for the feedback. I believe you may have found it since the issue is closed. Just some notes though; the solution uses bearer token to authenticate with twitter. We did put some notes here, https://docs.aws.amazon.com/solutions/latest/discovering-hot-topics-using-machine-learning/prerequisites.html. Let us know if that information was helpful.

Any other feedback on the solution, new feature requests or contributions, please feel free to reach out.
